### PR TITLE
Create some docs

### PR DESCRIPTION
**Pull request by takluyver**
This is quite minimal, because I think most of the information about the Jupyter command, environment variables, etc. should be in the overview docs, not here. But it seems like it should have
some API docs.

Should we document any of the constants in the paths module, e.g. SYSTEM_JUPYTER_PATH, as public API? Likewise, do we consider the API of the JupyterApp base class public?

### CODE REVIEW

**Comment by minrk** [comment]
I *don't* consider JupyterApp to be a public API, but it is an API we consume privately across Jupyter projects. I'm not sure about the constants. They can be relevant to packagers and test-environment mockers, but not really to users, who should only ever use the functions.

**Comment by takluyver** [comment]
That was roughly my thinking too. I'd prefer to err on the side of not publicly documenting things when we're in doubt.

**Comment by takluyver** [comment]
http://jupyter-core.readthedocs.org/en/latest/index.html

**Comment by minrk** [comment]
woo!

**Pull request merged**
