### PR TITLE
 properly handle unicode characters in home dirs

### PR DESCRIPTION
**Pull request by vit-tucek**
Sometimes users have home directories that contain unicode characters outside of ASCII (such as č). This leads to exception thrown in `migrate.py:migrate` namely in the line:
`        dst = dst_t.format(**env)`
because `jupyter_config_dir` and `jupyter_data_dir` do not return unicode.

### CODE REVIEW

**Comment by vit-tucek** [comment]
Failing because of missing `future` module. I've created another [patch](https://github.com/jupyter/jupyter_core/pull/132).

**Comment by embray** [comment]
You don't need to open new PRs.  You can update the existing ones by pushing new versions of a change to the existing branch using `git push -f` at the command line.

Nevertheless, I don't think this is the correct fix.  Can you post the full traceback and exception you get when trying to run the migrate script?

**Comment by vit-tucek** [comment]
Done. Now if only the devs would notice.

**Comment by minrk** [comment]
Sorry for the delay on this one. Merged with a small fix.

**Pull request merged**
