### PR TITLE
Use unicode everywhere, because unicode is good, python2 is bad

### PR DESCRIPTION
**Pull request by Carreau**
Pretty sure that will fix jupyter/notebook#646

Need to write a test.

### CODE REVIEW

**Comment by minrk** [comment]
I don't love using unicode_literals, since it results in some pretty surprising behavior, but if this is the most direct fix, +1. Looking forward to the test.

**Comment by Carreau** [comment]
> Looking forward to the test.

I'll investigate on monday.

**Comment by Carreau** [comment]
Ok, I have a failing test but that fails for the wrong thing :-P 

Will investigate deeper later.

**Comment by Carreau** [comment]
What a joy. 

os.envion on 3 have unicode values and keys that use `getsystemencoding`. 

use `environb` for bytes. 

Python2 has only `os.environ` it is not sure which one, seem to be bytes !

**Comment by willingc** [comment]
@Carreau For more joy and pain, http://nedbatchelder.com/text/unipain.html

**Comment by Carreau** [comment]
Yeah, I've read Ned's talk and watched the talk twice I'm annoyed because the fix is long and annoying. 

I would be in favor in not supporting python2.7+unicode home dirs.

As pointed by Aaron Meurer on Twitter, anyway you can't have set unicode env variable on windows, so I'm not sure it is worth pursuing on other platform.

**Comment by Carreau** [comment]
Ok, I gave up on writing for unicode home, though this still test the behavior for #646.

**Pull request merged**
