### PR TITLE
Scanning with CodeQL from GitHub

### PR DESCRIPTION
**Pull request by jasongrout**
See https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/enabling-code-scanning-for-a-repository

### CODE REVIEW

**Comment by jasongrout** [comment]
This fixes everything except the cyclic import flags. I think those are not valid (since one import is in a function), but I didn't think too deeply about and left it open.

https://github.com/jupyter/jupyter_core/security/code-scanning?query=tool%3ACodeQL+is%3Aopen+ref%3Arefs%2Fpull%2F202%2Fmerge

**Comment by jasongrout** [comment]
If someone wants to look through my fixes, and merge if they look good, that would be great.

**Review by blink1073 — APPROVED** [review]
👍🏼

**Comment by rgbkrk** [comment]
Wow, what a nice little cleanup. CodeQL is slick.

**Pull request merged**
