### PR TITLE
Changelog for 4.6.0

### PR DESCRIPTION
**Pull request by kevin-bates**

### CODE REVIEW

**Comment by kevin-bates** [comment]
@minrk (or whomever will be cutting the release) - we should hold off producing a release until https://github.com/jupyter/notebook/issues/4907 is resolved - since this has bearing on the `secure_write` implementation that was recently merged via #163.

**Comment by minrk** [comment]
Thanks! I'll be happy to cut a release once we can figure out jupyter/jupyter_client#479 /  jupyter/notebook#4907

**Comment by minrk** [comment]
@kevin-bates now that we have #166, are we clear to release 4.6?

**Comment by kevin-bates** [comment]
Yes, I believe so. Thank you @minrk.

**Comment by minrk** [comment]
Published 4.6.0

**Pull request merged**
